# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(497, 300)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(150, 140, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(300, 140, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.input1 = QtWidgets.QSpinBox(parent=Dialog)
        self.input1.setGeometry(QtCore.QRect(30, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input1.setFont(font)
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QSpinBox(parent=Dialog)
        self.input2.setGeometry(QtCore.QRect(190, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input2.setFont(font)
        self.input2.setObjectName("input2")
        self.output = QtWidgets.QTextBrowser(parent=Dialog)
        self.output.setGeometry(QtCore.QRect(340, 130, 131, 61))
        self.output.setObjectName("output")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculator"))
        self.label.setText(_translate("Dialog", "Input 1"))
        self.label_2.setText(_translate("Dialog", "Input 2"))
        self.label_3.setText(_translate("Dialog", "+"))
        self.label_4.setText(_translate("Dialog", "="))
        self.label_5.setText(_translate("Dialog", "Output"))
