# Form implementation generated from reading ui file 'frmGuess.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmGuess(object):
    def setupUi(self, frmGuess):
        frmGuess.setObjectName("frmGuess")
        frmGuess.resize(400, 300)
        self.guess_button = QtWidgets.QPushButton(parent=frmGuess)
        self.guess_button.setGeometry(QtCore.QRect(20, 60, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.guess_button.setFont(font)
        self.guess_button.setObjectName("guess_button")
        self.hint_button = QtWidgets.QPushButton(parent=frmGuess)
        self.hint_button.setGeometry(QtCore.QRect(190, 60, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hint_button.setFont(font)
        self.hint_button.setObjectName("hint_button")
        self.guessTextLabel = QtWidgets.QLabel(parent=frmGuess)
        self.guessTextLabel.setGeometry(QtCore.QRect(40, 160, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.guessTextLabel.setFont(font)
        self.guessTextLabel.setObjectName("guessTextLabel")
        self.timesGuessedLabel = QtWidgets.QLabel(parent=frmGuess)
        self.timesGuessedLabel.setGeometry(QtCore.QRect(230, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timesGuessedLabel.setFont(font)
        self.timesGuessedLabel.setText("")
        self.timesGuessedLabel.setObjectName("timesGuessedLabel")

        self.retranslateUi(frmGuess)
        QtCore.QMetaObject.connectSlotsByName(frmGuess)

    def retranslateUi(self, frmGuess):
        _translate = QtCore.QCoreApplication.translate
        frmGuess.setWindowTitle(_translate("frmGuess", "Guess a number between 1 and 100"))
        self.guess_button.setText(_translate("frmGuess", "Guess..."))
        self.hint_button.setText(_translate("frmGuess", "Give me a hint..."))
        self.guessTextLabel.setText(_translate("frmGuess", "Number of guesses :"))
