from bs4 import BeautifulSoup
import requests

url = "https://www.tutorialspoint.com/index.htm"
req = requests.get(url)

soup = BeautifulSoup(req.content, "html.parser")
print(soup.title)  # Tab title of the page

a_set=soup.find_all('a')

URL_list = []
for link in soup.find_all('a'):
    print(link.get('href'))
    URL_list.append(link.get('href'))
# Start :
# <h2 id="History">History</h2> # 1083

# End : # 1174
# <p>On 28 May 2019, the W3C announced that WHATWG would be the sole publisher of the HTML and DOM standards.<sup id="cite_ref-W3C_transfer_blog_67-0" class="reference"><a href="#cite_note-W3C_transfer_blog-67"><span class="cite-bracket">[</span>66<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_HTML_68-0" class="reference"><a href="#cite_note-W3C_transfer_HTML-68"><span class="cite-bracket">[</span>67<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_memo_69-0" class="reference"><a href="#cite_note-W3C_transfer_memo-69"><span class="cite-bracket">[</span>68<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_ZDNet_70-0" class="reference"><a href="#cite_note-W3C_transfer_ZDNet-70"><span class="cite-bracket">[</span>69<span class="cite-bracket">]</span></a></sup> The W3C and WHATWG had been publishing competing standards since 2012. While the W3C standard was identical to the WHATWG in 2007 the standards have since progressively diverged due to different design decisions.<sup id="cite_ref-W3C_forks_71-0" class="reference"><a href="#cite_note-W3C_forks-71"><span class="cite-bracket">[</span>70<span class="cite-bracket">]</span></a></sup> The WHATWG "Living Standard" had been the <i>de facto</i> web standard for some time.<sup id="cite_ref-72" class="reference"><a href="#cite_note-72"><span class="cite-bracket">[</span>71<span class="cite-bracket">]</span></a></sup>
# </p>

part_page = """
<div class="mw-heading mw-heading2"><h2 id="History">History</h2></div>
<div class="mw-heading mw-heading3"><h3 id="Development">Development</h3></div>
<figure class="mw-default-size mw-halign-right" typeof="mw:File/Thumb"><a href="/wiki/File:Tim_Berners-Lee_April_2009.jpg" class="mw-file-description"><img alt="Photograph of Tim Berners-Lee in April 2009" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tim_Berners-Lee_April_2009.jpg/250px-Tim_Berners-Lee_April_2009.jpg" decoding="async" width="190" height="262" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tim_Berners-Lee_April_2009.jpg/330px-Tim_Berners-Lee_April_2009.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tim_Berners-Lee_April_2009.jpg/500px-Tim_Berners-Lee_April_2009.jpg 2x" data-file-width="1195" data-file-height="1648"></a><figcaption><a href="/wiki/Tim_Berners-Lee" title="Tim Berners-Lee">Tim Berners-Lee</a> in April 2009</figcaption></figure>
<p>In 1980, <a href="/wiki/Physicist" title="Physicist">physicist</a> <a href="/wiki/Tim_Berners-Lee" title="Tim Berners-Lee">Tim Berners-Lee</a>, a contractor at <a href="/wiki/CERN" title="CERN">CERN</a>, proposed and prototyped <a href="/wiki/ENQUIRE" title="ENQUIRE">ENQUIRE</a>, a system for CERN researchers to use and share documents. In 1989, Berners-Lee wrote a memo proposing an <a href="/wiki/Internet" title="Internet">Internet</a>-based <a href="/wiki/Hypertext" title="Hypertext">hypertext</a> system.<sup id="cite_ref-5" class="reference"><a href="#cite_note-5"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup> Berners-Lee specified HTML and wrote the browser and server software in late 1990. That year, Berners-Lee and CERN <a href="/wiki/Data_system" title="Data system">data systems</a> engineer <a href="/wiki/Robert_Cailliau" title="Robert Cailliau">Robert Cailliau</a> collaborated on a joint request for funding, but the project was not formally adopted by CERN. In his personal notes of 1990, Berners-Lee listed "some of the many areas in which hypertext is used"; an <a href="/wiki/Encyclopedia" title="Encyclopedia">encyclopedia</a> is the first entry.<sup id="cite_ref-6" class="reference"><a href="#cite_note-6"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</p><p>The first publicly available description of HTML was a document called "HTML Tags",<sup id="cite_ref-7" class="reference"><a href="#cite_note-7"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup> first mentioned on the Internet by Tim Berners-Lee in late 1991.<sup id="cite_ref-tagshtml_8-0" class="reference"><a href="#cite_note-tagshtml-8"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-9" class="reference"><a href="#cite_note-9"><span class="cite-bracket">[</span>8<span class="cite-bracket">]</span></a></sup> It describes 18 elements comprising the initial, relatively simple design of HTML. Except for the hyperlink tag, these were strongly influenced by <a href="/wiki/CERN_SGML" title="CERN SGML">CERN SGML</a>, an in-house <a href="/wiki/Standard_Generalized_Markup_Language" title="Standard Generalized Markup Language">Standard Generalized Markup Language</a> (SGML)-based documentation format at CERN. Eleven of these elements still exist in HTML 4.<sup id="cite_ref-10" class="reference"><a href="#cite_note-10"><span class="cite-bracket">[</span>9<span class="cite-bracket">]</span></a></sup>
</p><p>HTML is a <a href="/wiki/Markup_language" title="Markup language">markup language</a> that <a href="/wiki/Web_browser" title="Web browser">web browsers</a> use to interpret and <a href="/wiki/Typesetting" title="Typesetting">compose</a> text, images, and other material into visible or audible web pages. Default characteristics for every item of HTML markup are defined in the browser, and these characteristics can be altered or enhanced by the web page designer's additional use of <a href="/wiki/CSS" title="CSS">CSS</a>. Many of the text elements are mentioned in the 1988 ISO technical report TR 9537 <i>Techniques for using SGML</i>, which describes the features of early text formatting languages such as that used by the <a href="/wiki/TYPSET_and_RUNOFF" title="TYPSET and RUNOFF">RUNOFF command</a> developed in the early 1960s for the <a href="/wiki/Compatible_Time-Sharing_System" title="Compatible Time-Sharing System">CTSS</a> (Compatible Time-Sharing System) operating system. These formatting commands were derived from the commands used by typesetters to manually format documents. However, the SGML concept of generalized markup is based on elements (nested annotated ranges with attributes) rather than merely print effects, with separate structure and markup. HTML has been progressively moved in this direction with CSS.
</p><p>Berners-Lee considered HTML to be an application of SGML. It was formally defined as such by the <a href="/wiki/Internet_Engineering_Task_Force" title="Internet Engineering Task Force">Internet Engineering Task Force</a> (IETF) with the mid-1993 publication of the first proposal for an HTML specification, the "Hypertext Markup Language (HTML)" Internet Draft by Berners-Lee and <a href="/wiki/Dan_Connolly_(computer_scientist)" title="Dan Connolly (computer scientist)">Dan Connolly</a>, which included an SGML <a href="/wiki/Document_type_definition" title="Document type definition">Document type definition</a> to define the syntax.<sup id="cite_ref-11" class="reference"><a href="#cite_note-11"><span class="cite-bracket">[</span>10<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-12" class="reference"><a href="#cite_note-12"><span class="cite-bracket">[</span>11<span class="cite-bracket">]</span></a></sup> The draft expired after six months, but was notable for its acknowledgment of the <a href="/wiki/Mosaic_(web_browser)" class="mw-redirect" title="Mosaic (web browser)">NCSA Mosaic</a> browser's custom tag for embedding in-line images, reflecting the IETF's philosophy of basing standards on successful prototypes. Similarly, <a href="/wiki/Dave_Raggett" title="Dave Raggett">Dave Raggett</a>'s competing Internet Draft, "HTML+ (Hypertext Markup Format)", from late 1993, suggested standardizing already-implemented features like tables and fill-out forms.<sup id="cite_ref-html+_13-0" class="reference"><a href="#cite_note-html+-13"><span class="cite-bracket">[</span>12<span class="cite-bracket">]</span></a></sup>
</p><p>After the HTML and HTML+ drafts expired in early 1994, the IETF created an HTML Working Group. In 1995, this working group completed "HTML 2.0", the first HTML specification intended to be treated as a standard against which future implementations should be based.<sup id="cite_ref-14" class="reference"><a href="#cite_note-14"><span class="cite-bracket">[</span>13<span class="cite-bracket">]</span></a></sup>
</p><p>Further development under the auspices of the IETF was stalled by competing interests. Since 1996,<sup class="plainlinks noexcerpt noprint asof-tag update" style="display:none;"><a class="external text" href="https://en.wikipedia.org/w/index.php?title=HTML&amp;action=edit">[update]</a></sup> the HTML specifications have been maintained, with input from commercial software vendors, by the <a href="/wiki/World_Wide_Web_Consortium" title="World Wide Web Consortium">World Wide Web Consortium</a> (W3C).<sup id="cite_ref-raggett_15-0" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> In 2000, HTML became an international standard (<a href="/wiki/International_Organization_for_Standardization" title="International Organization for Standardization">ISO</a>/<a href="/wiki/International_Electrotechnical_Commission" title="International Electrotechnical Commission">IEC</a> 15445:2000). HTML 4.01 was published in late 1999, with further errata published through 2001. In 2004, development began on HTML5 in the <a href="/wiki/Web_Hypertext_Application_Technology_Working_Group" class="mw-redirect" title="Web Hypertext Application Technology Working Group">Web Hypertext Application Technology Working Group</a> (WHATWG), which became a joint deliverable with the W3C in 2008, and was completed and standardized on 28 October 2014.<sup id="cite_ref-16" class="reference"><a href="#cite_note-16"><span class="cite-bracket">[</span>15<span class="cite-bracket">]</span></a></sup>
</p>
<div class="mw-heading mw-heading3"><h3 id="HTML_version_timeline">HTML version timeline</h3></div>
<div class="mw-heading mw-heading4"><h4 id="HTML_2">HTML 2</h4></div>
<dl><dd><dl><dt>November 24, 1995</dt>
<dd>HTML 2.0 was published as <style data-mw-deduplicate="TemplateStyles:r1238218222">.mw-parser-output cite.citation{font-style:inherit;word-wrap:break-word}.mw-parser-output .citation q{quotes:"\"""\"""'""'"}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}.mw-parser-output .id-lock-free.id-lock-free a{background:url("//upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-limited.id-lock-limited a,.mw-parser-output .id-lock-registration.id-lock-registration a{background:url("//upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-subscription.id-lock-subscription a{background:url("//upload.wikimedia.org/wikipedia/commons/a/aa/Lock-red-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .cs1-ws-icon a{background:url("//upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg")right 0.1em center/12px no-repeat}body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-free a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-limited a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-registration a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-subscription a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .cs1-ws-icon a{background-size:contain;padding:0 1em 0 0}.mw-parser-output .cs1-code{color:inherit;background:inherit;border:none;padding:inherit}.mw-parser-output .cs1-hidden-error{display:none;color:var(--color-error,#d33)}.mw-parser-output .cs1-visible-error{color:var(--color-error,#d33)}.mw-parser-output .cs1-maint{display:none;color:#085;margin-left:0.3em}.mw-parser-output .cs1-kern-left{padding-left:0.2em}.mw-parser-output .cs1-kern-right{padding-right:0.2em}.mw-parser-output .citation .mw-selflink{font-weight:inherit}@media screen{.mw-parser-output .cs1-format{font-size:95%}html.skin-theme-clientpref-night .mw-parser-output .cs1-maint{color:#18911f}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .cs1-maint{color:#18911f}}</style><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1866">1866</a>. Supplemental <a href="/wiki/Request_for_Comments" title="Request for Comments">RFCs</a> added capabilities:
<ul><li>November 25, 1995: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1867">1867</a> (form-based file upload)</li>
<li>May 1996: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1942">1942</a> (tables)</li>
<li>August 1996: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1980">1980</a> (client-side image maps)</li>
<li>January 1997: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc2070">2070</a> (<a href="/wiki/Internationalization_and_localization" title="Internationalization and localization">internationalization</a>)</li></ul></dd></dl></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="HTML_3">HTML 3</h4></div>
<dl><dd><dl><dt>January 14, 1997</dt>
<dd>HTML 3.2<sup id="cite_ref-17" class="reference"><a href="#cite_note-17"><span class="cite-bracket">[</span>16<span class="cite-bracket">]</span></a></sup> was published as a <a href="/wiki/W3C_Recommendation" class="mw-redirect" title="W3C Recommendation">W3C Recommendation</a>. It was the first version developed and standardized exclusively by the W3C, as the IETF had closed its HTML Working Group on September 12, 1996.<sup id="cite_ref-18" class="reference"><a href="#cite_note-18"><span class="cite-bracket">[</span>17<span class="cite-bracket">]</span></a></sup></dd>
<dd>Initially code-named "Wilbur",<sup id="cite_ref-engelfriet_19-0" class="reference"><a href="#cite_note-engelfriet-19"><span class="cite-bracket">[</span>18<span class="cite-bracket">]</span></a></sup> HTML 3.2 dropped math formulas entirely, reconciled overlap among various proprietary extensions and adopted most of <a href="/wiki/Netscape" title="Netscape">Netscape</a>'s visual markup tags. Netscape's <a href="/wiki/Blink_element" title="Blink element">blink element</a> and <a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>'s <a href="/wiki/Marquee_element" title="Marquee element">marquee element</a> were omitted due to a mutual agreement between the two companies.<sup id="cite_ref-raggett_15-1" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> A markup for mathematical formulas similar to that of HTML was standardized 14 months later in <a href="/wiki/MathML" title="MathML">MathML</a>.</dd></dl></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="HTML_4">HTML 4</h4></div>
<dl><dd><dl><dt>December 18, 1997</dt>
<dd>HTML 4.0<sup id="cite_ref-20" class="reference"><a href="#cite_note-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation. It offers three variations:</dd></dl>
<dl><dt><ul><li>Strict, in which deprecated elements are forbidden</li>
<li>Transitional, in which deprecated elements are allowed</li>
<li>Frameset, in which mostly only <a href="/wiki/Framing_(World_Wide_Web)" class="mw-redirect" title="Framing (World Wide Web)">frame</a> related elements are allowed.</li></ul></dt></dl></dd>
<dd>Initially code-named "Cougar",<sup id="cite_ref-engelfriet_19-1" class="reference"><a href="#cite_note-engelfriet-19"><span class="cite-bracket">[</span>18<span class="cite-bracket">]</span></a></sup> HTML 4.0 adopted many browser-specific element types and attributes, but also sought to phase out Netscape's visual markup features by marking them as <a href="/wiki/Deprecation" title="Deprecation">deprecated</a> in favor of style sheets. HTML 4 is an SGML application conforming to ISO 8879&nbsp;– SGML.<sup id="cite_ref-21" class="reference"><a href="#cite_note-21"><span class="cite-bracket">[</span>20<span class="cite-bracket">]</span></a></sup>
<dl><dt>April 24, 1998</dt></dl></dd>
<dd>HTML 4.0<sup id="cite_ref-22" class="reference"><a href="#cite_note-22"><span class="cite-bracket">[</span>21<span class="cite-bracket">]</span></a></sup> was reissued with minor edits without incrementing the version number.
<dl><dt>December 24, 1999</dt>
<dd>HTML 4.01<sup id="cite_ref-23" class="reference"><a href="#cite_note-23"><span class="cite-bracket">[</span>22<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation. It offers the same three variations as HTML 4.0 and its last errata<sup id="cite_ref-24" class="reference"><a href="#cite_note-24"><span class="cite-bracket">[</span>23<span class="cite-bracket">]</span></a></sup> were published on May 12, 2001.</dd>
<dt>May 2000</dt>
<dd>ISO/IEC 15445:2000<sup id="cite_ref-iso-html_25-0" class="reference"><a href="#cite_note-iso-html-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup> ("<a href="/wiki/International_Organization_for_Standardization" title="International Organization for Standardization">ISO</a> HTML", based on HTML 4.01 Strict) was published as an ISO/IEC international standard.<sup id="cite_ref-26" class="reference"><a href="#cite_note-26"><span class="cite-bracket">[</span>25<span class="cite-bracket">]</span></a></sup> In the ISO, this standard is in the domain of the <a href="/wiki/ISO/IEC_JTC_1/SC_34" title="ISO/IEC JTC 1/SC 34">ISO/IEC JTC 1/SC 34</a> (ISO/IEC Joint Technical Committee 1, Subcommittee 34&nbsp;– Document description and processing languages).<sup id="cite_ref-iso-html_25-1" class="reference"><a href="#cite_note-iso-html-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup></dd></dl>
<dl><dt><dl><dd>After HTML 4.01, there were no new versions of HTML for many years, as the development of the parallel, XML-based language XHTML occupied the W3C's HTML Working Group.</dd></dl></dt></dl></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="HTML_5">HTML 5</h4></div>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1236090951"><div role="note" class="hatnote navigation-not-searchable">Main article: <a href="/wiki/HTML5" title="HTML5">HTML5</a></div>
<dl><dd><dl><dt>October 28, 2014</dt>
<dd>HTML5<sup id="cite_ref-27" class="reference"><a href="#cite_note-27"><span class="cite-bracket">[</span>26<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation.<sup id="cite_ref-28" class="reference"><a href="#cite_note-28"><span class="cite-bracket">[</span>27<span class="cite-bracket">]</span></a></sup></dd>
<dt>November 1, 2016</dt>
<dd>HTML 5.1<sup id="cite_ref-29" class="reference"><a href="#cite_note-29"><span class="cite-bracket">[</span>28<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation.<sup id="cite_ref-30" class="reference"><a href="#cite_note-30"><span class="cite-bracket">[</span>29<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-31" class="reference"><a href="#cite_note-31"><span class="cite-bracket">[</span>30<span class="cite-bracket">]</span></a></sup></dd>
<dt>December 14, 2017</dt>
<dd>HTML 5.2<sup id="cite_ref-32" class="reference"><a href="#cite_note-32"><span class="cite-bracket">[</span>31<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation.<sup id="cite_ref-33" class="reference"><a href="#cite_note-33"><span class="cite-bracket">[</span>32<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-34" class="reference"><a href="#cite_note-34"><span class="cite-bracket">[</span>33<span class="cite-bracket">]</span></a></sup></dd></dl></dd></dl>
<div class="mw-heading mw-heading3"><h3 id="HTML_draft_version_timeline">HTML draft version timeline</h3></div>
<dl><dt>October 1991</dt>
<dd><i>HTML Tags</i>,<sup id="cite_ref-tagshtml_8-1" class="reference"><a href="#cite_note-tagshtml-8"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup> an informal CERN document listing 18 HTML tags, was first mentioned in public.</dd>
<dt>June 1992</dt>
<dd>First informal draft of the HTML DTD,<sup id="cite_ref-35" class="reference"><a href="#cite_note-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup> with seven subsequent revisions (July 15, August 6, August 18, November 17, November 19, November 20, November 22)<sup id="cite_ref-36" class="reference"><a href="#cite_note-36"><span class="cite-bracket">[</span>35<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-37" class="reference"><a href="#cite_note-37"><span class="cite-bracket">[</span>36<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-html11_38-0" class="reference"><a href="#cite_note-html11-38"><span class="cite-bracket">[</span>37<span class="cite-bracket">]</span></a></sup></dd>
<dt>November 1992</dt>
<dd>HTML DTD 1.1 (the first with a version number, based on RCS revisions, which start with 1.1 rather than 1.0), an informal draft<sup id="cite_ref-html11_38-1" class="reference"><a href="#cite_note-html11-38"><span class="cite-bracket">[</span>37<span class="cite-bracket">]</span></a></sup></dd>
<dt>June 1993</dt>
<dd>Hypertext Markup Language<sup id="cite_ref-39" class="reference"><a href="#cite_note-39"><span class="cite-bracket">[</span>38<span class="cite-bracket">]</span></a></sup> was published by the <a href="/wiki/Internet_Engineering_Task_Force" title="Internet Engineering Task Force">IETF</a> IIIR Working Group as an Internet Draft (a rough proposal for a standard). It was replaced by a second version<sup id="cite_ref-ietfiiir_40-0" class="reference"><a href="#cite_note-ietfiiir-40"><span class="cite-bracket">[</span>39<span class="cite-bracket">]</span></a></sup> one month later.</dd>
<dt>November 1993</dt>
<dd><a rel="nofollow" class="external text" href="https://www.w3.org/MarkUp/HTMLPlus/htmlplus_1.html">HTML+</a> was published by the IETF as an Internet Draft and was a competing proposal to the Hypertext Markup Language draft. It expired in July 1994.<sup id="cite_ref-41" class="reference"><a href="#cite_note-41"><span class="cite-bracket">[</span>40<span class="cite-bracket">]</span></a></sup></dd>
<dt>November 1994</dt>
<dd>First draft (revision 00) of HTML 2.0 published by IETF itself<sup id="cite_ref-42" class="reference"><a href="#cite_note-42"><span class="cite-bracket">[</span>41<span class="cite-bracket">]</span></a></sup> (called as "HTML 2.0" from revision 02<sup id="cite_ref-43" class="reference"><a href="#cite_note-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup>), that finally led to the publication of <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1866">1866</a> in November 1995.<sup id="cite_ref-rfc1866_44-0" class="reference"><a href="#cite_note-rfc1866-44"><span class="cite-bracket">[</span>43<span class="cite-bracket">]</span></a></sup></dd>
<dt>April 1995 (authored March 1995)</dt>
<dd>HTML 3.0<sup id="cite_ref-45" class="reference"><a href="#cite_note-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup> was proposed as a standard to the IETF, but the proposal expired five months later (28 September 1995)<sup id="cite_ref-html30cover_46-0" class="reference"><a href="#cite_note-html30cover-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup> without further action. It included many of the capabilities that were in Raggett's HTML+ proposal, such as support for tables, text flow around figures, and the display of complex mathematical formulas.<sup id="cite_ref-html30cover_46-1" class="reference"><a href="#cite_note-html30cover-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>W3C began development of its own <a href="/wiki/Arena_(web_browser)" title="Arena (web browser)">Arena browser</a> as a <a href="/wiki/Test_bed" class="mw-redirect" title="Test bed">test bed</a> for HTML 3 and Cascading Style Sheets,<sup id="cite_ref-47" class="reference"><a href="#cite_note-47"><span class="cite-bracket">[</span>46<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-48" class="reference"><a href="#cite_note-48"><span class="cite-bracket">[</span>47<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-49" class="reference"><a href="#cite_note-49"><span class="cite-bracket">[</span>48<span class="cite-bracket">]</span></a></sup> but HTML 3.0 did not succeed for several reasons. The draft was considered very large at 150 pages and the pace of browser development, as well as the number of interested parties, had outstripped the resources of the IETF.<sup id="cite_ref-raggett_15-2" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> Browser vendors, including Microsoft and Netscape at the time, chose to implement different subsets of HTML 3's draft features as well as to introduce their own extensions to it.<sup id="cite_ref-raggett_15-3" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> (See <a href="/wiki/Browser_wars" title="Browser wars">browser wars</a>.) These included extensions to control stylistic aspects of documents, contrary to the "belief [of the academic engineering community] that such things as text color, background texture, font size, and font face were definitely outside the scope of a language when their only intent was to specify how a document would be organized."<sup id="cite_ref-raggett_15-4" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> Dave Raggett, who has been a W3C Fellow for many years, has commented for example: "To a certain extent, Microsoft built its business on the Web by extending HTML features."<sup id="cite_ref-raggett_15-5" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup></dd></dl>
<figure class="mw-default-size mw-halign-right" typeof="mw:File/Thumb"><a href="/wiki/File:HTML5_logo_and_wordmark.svg" class="mw-file-description"><img alt="Official HTML5 logo" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/250px-HTML5_logo_and_wordmark.svg.png" decoding="async" width="190" height="190" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/330px-HTML5_logo_and_wordmark.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/500px-HTML5_logo_and_wordmark.svg.png 2x" data-file-width="512" data-file-height="512"></a><figcaption>Logo of HTML5</figcaption></figure>
<dl><dt>January 2008</dt>
<dd><a href="/wiki/HTML5" title="HTML5">HTML5</a> was published as a <a href="/wiki/World_Wide_Web_Consortium#Certification" title="World Wide Web Consortium">Working Draft</a> by the W3C.<sup id="cite_ref-50" class="reference"><a href="#cite_note-50"><span class="cite-bracket">[</span>49<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>Although its syntax closely resembles that of <a href="/wiki/SGML" class="mw-redirect" title="SGML">SGML</a>, <a href="/wiki/HTML5" title="HTML5">HTML5</a> has abandoned any attempt to be an SGML application and has explicitly defined its own "html" serialization, in addition to an alternative XML-based XHTML5 serialization.<sup id="cite_ref-51" class="reference"><a href="#cite_note-51"><span class="cite-bracket">[</span>50<span class="cite-bracket">]</span></a></sup></dd>
<dt>2011&nbsp;HTML5 – Last Call</dt>
<dd></dd>
<dt></dt>
<dd>On 14 February 2011, the W3C extended the charter of its HTML Working Group with clear milestones for HTML5. In May 2011, the working group advanced HTML5 to "Last Call", an invitation to communities inside and outside W3C to confirm the technical soundness of the specification. The W3C developed a comprehensive test suite to achieve broad interoperability for the full specification by 2014, which was the target date for recommendation.<sup id="cite_ref-w3c2014_52-0" class="reference"><a href="#cite_note-w3c2014-52"><span class="cite-bracket">[</span>51<span class="cite-bracket">]</span></a></sup> In January 2011, the WHATWG renamed its "HTML5" living standard to "HTML". The W3C nevertheless continued its project to release HTML5.<sup id="cite_ref-53" class="reference"><a href="#cite_note-53"><span class="cite-bracket">[</span>52<span class="cite-bracket">]</span></a></sup></dd>
<dt>2012&nbsp;HTML5 – Candidate Recommendation</dt>
<dd></dd>
<dt></dt>
<dd>In July 2012, WHATWG and <a href="/wiki/W3C" class="mw-redirect" title="W3C">W3C</a> decided on a degree of separation. W3C will continue the HTML5 specification work, focusing on a single definitive standard, which is considered a "snapshot" by WHATWG. The WHATWG organization will continue its work with HTML5 as a "Living Standard". The concept of a living standard is that it is never complete and is always being updated and improved. New features can be added but functionality will not be removed.<sup id="cite_ref-54" class="reference"><a href="#cite_note-54"><span class="cite-bracket">[</span>53<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>In December 2012, W3C designated HTML5 as a Candidate Recommendation.<sup id="cite_ref-55" class="reference"><a href="#cite_note-55"><span class="cite-bracket">[</span>54<span class="cite-bracket">]</span></a></sup> The criterion for advancement to <a href="/wiki/W3C_recommendation#W3C_recommendation_(REC)" class="mw-redirect" title="W3C recommendation">W3C Recommendation</a> is "two 100% complete and fully interoperable implementations".<sup id="cite_ref-W3Crec_56-0" class="reference"><a href="#cite_note-W3Crec-56"><span class="cite-bracket">[</span>55<span class="cite-bracket">]</span></a></sup></dd>
<dt>2014&nbsp;HTML5 – Proposed Recommendation and Recommendation</dt>
<dd></dd>
<dt></dt>
<dd>In September 2014, W3C moved HTML5 to Proposed Recommendation.<sup id="cite_ref-57" class="reference"><a href="#cite_note-57"><span class="cite-bracket">[</span>56<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>On 28 October 2014, HTML5 was released as a stable W3C Recommendation,<sup id="cite_ref-58" class="reference"><a href="#cite_note-58"><span class="cite-bracket">[</span>57<span class="cite-bracket">]</span></a></sup> meaning the specification process is complete.<sup id="cite_ref-finalars_59-0" class="reference"><a href="#cite_note-finalars-59"><span class="cite-bracket">[</span>58<span class="cite-bracket">]</span></a></sup></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="XHTML_versions">XHTML versions</h4></div>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1236090951"><div role="note" class="hatnote navigation-not-searchable">Main article: <a href="/wiki/XHTML" title="XHTML">XHTML</a></div>
<p>XHTML is a separate language that began as a reformulation of HTML 4.01 using <a href="/wiki/XML" title="XML">XML</a> 1.0. It is now referred to as <i>the XML syntax for HTML</i> and is no longer being developed as a separate standard.<sup id="cite_ref-60" class="reference"><a href="#cite_note-60"><span class="cite-bracket">[</span>59<span class="cite-bracket">]</span></a></sup>
</p>
<ul><li>XHTML 1.0 was published as a W3C Recommendation on January 26, 2000,<sup id="cite_ref-61" class="reference"><a href="#cite_note-61"><span class="cite-bracket">[</span>60<span class="cite-bracket">]</span></a></sup> and was later revised and republished on August 1, 2002. It offers the same three variations as HTML 4.0 and 4.01, reformulated in XML, with minor restrictions.</li>
<li>XHTML 1.1<sup id="cite_ref-62" class="reference"><a href="#cite_note-62"><span class="cite-bracket">[</span>61<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation on May 31, 2001. It is based on XHTML 1.0 Strict, but includes minor changes, can be customized, and is reformulated using modules in the W3C recommendation "Modularization of XHTML", which was published on April 10, 2001.<sup id="cite_ref-63" class="reference"><a href="#cite_note-63"><span class="cite-bracket">[</span>62<span class="cite-bracket">]</span></a></sup></li>
<li>XHTML 2.0 was a working draft. Work on it was abandoned in 2009 in favor of work on <a href="/wiki/HTML5" title="HTML5">HTML5</a> and <a href="/wiki/XHTML#XHTML5" title="XHTML">XHTML5</a>.<sup id="cite_ref-64" class="reference"><a href="#cite_note-64"><span class="cite-bracket">[</span>63<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-65" class="reference"><a href="#cite_note-65"><span class="cite-bracket">[</span>64<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-66" class="reference"><a href="#cite_note-66"><span class="cite-bracket">[</span>65<span class="cite-bracket">]</span></a></sup> XHTML 2.0 was incompatible with XHTML 1.x and, therefore, would be more accurately characterized as an XHTML-inspired new language than an update to XHTML 1.x.</li></ul>
<div class="mw-heading mw-heading3"><h3 id="Transition_of_HTML_publication_to_WHATWG">Transition of HTML publication to WHATWG</h3></div>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1236090951"><div role="note" class="hatnote navigation-not-searchable">See also: <a href="/wiki/HTML5#W3C_and_WHATWG_conflict" title="HTML5">HTML5 §&nbsp;W3C and WHATWG conflict</a></div>
<p>On 28 May 2019, the W3C announced that WHATWG would be the sole publisher of the HTML and DOM standards.<sup id="cite_ref-W3C_transfer_blog_67-0" class="reference"><a href="#cite_note-W3C_transfer_blog-67"><span class="cite-bracket">[</span>66<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_HTML_68-0" class="reference"><a href="#cite_note-W3C_transfer_HTML-68"><span class="cite-bracket">[</span>67<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_memo_69-0" class="reference"><a href="#cite_note-W3C_transfer_memo-69"><span class="cite-bracket">[</span>68<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_ZDNet_70-0" class="reference"><a href="#cite_note-W3C_transfer_ZDNet-70"><span class="cite-bracket">[</span>69<span class="cite-bracket">]</span></a></sup> The W3C and WHATWG had been publishing competing standards since 2012. While the W3C standard was identical to the WHATWG in 2007 the standards have since progressively diverged due to different design decisions.<sup id="cite_ref-W3C_forks_71-0" class="reference"><a href="#cite_note-W3C_forks-71"><span class="cite-bracket">[</span>70<span class="cite-bracket">]</span></a></sup> The WHATWG "Living Standard" had been the <i>de facto</i> web standard for some time.<sup id="cite_ref-72" class="reference"><a href="#cite_note-72"><span class="cite-bracket">[</span>71<span class="cite-bracket">]</span></a></sup>
</p>
"""


#
part_page = """
<div class="mw-heading mw-heading3"><h3 id="Development">Development</h3></div>
<figure class="mw-default-size mw-halign-right" typeof="mw:File/Thumb"><a href="/wiki/File:Tim_Berners-Lee_April_2009.jpg" class="mw-file-description"><img alt="Photograph of Tim Berners-Lee in April 2009" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tim_Berners-Lee_April_2009.jpg/250px-Tim_Berners-Lee_April_2009.jpg" decoding="async" width="190" height="262" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tim_Berners-Lee_April_2009.jpg/330px-Tim_Berners-Lee_April_2009.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tim_Berners-Lee_April_2009.jpg/500px-Tim_Berners-Lee_April_2009.jpg 2x" data-file-width="1195" data-file-height="1648"></a><figcaption><a href="/wiki/Tim_Berners-Lee" title="Tim Berners-Lee">Tim Berners-Lee</a> in April 2009</figcaption></figure>
<p>In 1980, <a href="/wiki/Physicist" title="Physicist">physicist</a> <a href="/wiki/Tim_Berners-Lee" title="Tim Berners-Lee">Tim Berners-Lee</a>, a contractor at <a href="/wiki/CERN" title="CERN">CERN</a>, proposed and prototyped <a href="/wiki/ENQUIRE" title="ENQUIRE">ENQUIRE</a>, a system for CERN researchers to use and share documents. In 1989, Berners-Lee wrote a memo proposing an <a href="/wiki/Internet" title="Internet">Internet</a>-based <a href="/wiki/Hypertext" title="Hypertext">hypertext</a> system.<sup id="cite_ref-5" class="reference"><a href="#cite_note-5"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup> Berners-Lee specified HTML and wrote the browser and server software in late 1990. That year, Berners-Lee and CERN <a href="/wiki/Data_system" title="Data system">data systems</a> engineer <a href="/wiki/Robert_Cailliau" title="Robert Cailliau">Robert Cailliau</a> collaborated on a joint request for funding, but the project was not formally adopted by CERN. In his personal notes of 1990, Berners-Lee listed "some of the many areas in which hypertext is used"; an <a href="/wiki/Encyclopedia" title="Encyclopedia">encyclopedia</a> is the first entry.<sup id="cite_ref-6" class="reference"><a href="#cite_note-6"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</p><p>The first publicly available description of HTML was a document called "HTML Tags",<sup id="cite_ref-7" class="reference"><a href="#cite_note-7"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup> first mentioned on the Internet by Tim Berners-Lee in late 1991.<sup id="cite_ref-tagshtml_8-0" class="reference"><a href="#cite_note-tagshtml-8"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-9" class="reference"><a href="#cite_note-9"><span class="cite-bracket">[</span>8<span class="cite-bracket">]</span></a></sup> It describes 18 elements comprising the initial, relatively simple design of HTML. Except for the hyperlink tag, these were strongly influenced by <a href="/wiki/CERN_SGML" title="CERN SGML">CERN SGML</a>, an in-house <a href="/wiki/Standard_Generalized_Markup_Language" title="Standard Generalized Markup Language">Standard Generalized Markup Language</a> (SGML)-based documentation format at CERN. Eleven of these elements still exist in HTML 4.<sup id="cite_ref-10" class="reference"><a href="#cite_note-10"><span class="cite-bracket">[</span>9<span class="cite-bracket">]</span></a></sup>
</p><p>HTML is a <a href="/wiki/Markup_language" title="Markup language">markup language</a> that <a href="/wiki/Web_browser" title="Web browser">web browsers</a> use to interpret and <a href="/wiki/Typesetting" title="Typesetting">compose</a> text, images, and other material into visible or audible web pages. Default characteristics for every item of HTML markup are defined in the browser, and these characteristics can be altered or enhanced by the web page designer's additional use of <a href="/wiki/CSS" title="CSS">CSS</a>. Many of the text elements are mentioned in the 1988 ISO technical report TR 9537 <i>Techniques for using SGML</i>, which describes the features of early text formatting languages such as that used by the <a href="/wiki/TYPSET_and_RUNOFF" title="TYPSET and RUNOFF">RUNOFF command</a> developed in the early 1960s for the <a href="/wiki/Compatible_Time-Sharing_System" title="Compatible Time-Sharing System">CTSS</a> (Compatible Time-Sharing System) operating system. These formatting commands were derived from the commands used by typesetters to manually format documents. However, the SGML concept of generalized markup is based on elements (nested annotated ranges with attributes) rather than merely print effects, with separate structure and markup. HTML has been progressively moved in this direction with CSS.
</p><p>Berners-Lee considered HTML to be an application of SGML. It was formally defined as such by the <a href="/wiki/Internet_Engineering_Task_Force" title="Internet Engineering Task Force">Internet Engineering Task Force</a> (IETF) with the mid-1993 publication of the first proposal for an HTML specification, the "Hypertext Markup Language (HTML)" Internet Draft by Berners-Lee and <a href="/wiki/Dan_Connolly_(computer_scientist)" title="Dan Connolly (computer scientist)">Dan Connolly</a>, which included an SGML <a href="/wiki/Document_type_definition" title="Document type definition">Document type definition</a> to define the syntax.<sup id="cite_ref-11" class="reference"><a href="#cite_note-11"><span class="cite-bracket">[</span>10<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-12" class="reference"><a href="#cite_note-12"><span class="cite-bracket">[</span>11<span class="cite-bracket">]</span></a></sup> The draft expired after six months, but was notable for its acknowledgment of the <a href="/wiki/Mosaic_(web_browser)" class="mw-redirect" title="Mosaic (web browser)">NCSA Mosaic</a> browser's custom tag for embedding in-line images, reflecting the IETF's philosophy of basing standards on successful prototypes. Similarly, <a href="/wiki/Dave_Raggett" title="Dave Raggett">Dave Raggett</a>'s competing Internet Draft, "HTML+ (Hypertext Markup Format)", from late 1993, suggested standardizing already-implemented features like tables and fill-out forms.<sup id="cite_ref-html+_13-0" class="reference"><a href="#cite_note-html+-13"><span class="cite-bracket">[</span>12<span class="cite-bracket">]</span></a></sup>
</p><p>After the HTML and HTML+ drafts expired in early 1994, the IETF created an HTML Working Group. In 1995, this working group completed "HTML 2.0", the first HTML specification intended to be treated as a standard against which future implementations should be based.<sup id="cite_ref-14" class="reference"><a href="#cite_note-14"><span class="cite-bracket">[</span>13<span class="cite-bracket">]</span></a></sup>
</p><p>Further development under the auspices of the IETF was stalled by competing interests. Since 1996,<sup class="plainlinks noexcerpt noprint asof-tag update" style="display:none;"><a class="external text" href="https://en.wikipedia.org/w/index.php?title=HTML&amp;action=edit">[update]</a></sup> the HTML specifications have been maintained, with input from commercial software vendors, by the <a href="/wiki/World_Wide_Web_Consortium" title="World Wide Web Consortium">World Wide Web Consortium</a> (W3C).<sup id="cite_ref-raggett_15-0" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> In 2000, HTML became an international standard (<a href="/wiki/International_Organization_for_Standardization" title="International Organization for Standardization">ISO</a>/<a href="/wiki/International_Electrotechnical_Commission" title="International Electrotechnical Commission">IEC</a> 15445:2000). HTML 4.01 was published in late 1999, with further errata published through 2001. In 2004, development began on HTML5 in the <a href="/wiki/Web_Hypertext_Application_Technology_Working_Group" class="mw-redirect" title="Web Hypertext Application Technology Working Group">Web Hypertext Application Technology Working Group</a> (WHATWG), which became a joint deliverable with the W3C in 2008, and was completed and standardized on 28 October 2014.<sup id="cite_ref-16" class="reference"><a href="#cite_note-16"><span class="cite-bracket">[</span>15<span class="cite-bracket">]</span></a></sup>
</p>
<div class="mw-heading mw-heading3"><h3 id="HTML_version_timeline">HTML version timeline</h3></div>
<div class="mw-heading mw-heading4"><h4 id="HTML_2">HTML 2</h4></div>
<dl><dd><dl><dt>November 24, 1995</dt>
<dd>HTML 2.0 was published as <style data-mw-deduplicate="TemplateStyles:r1238218222">.mw-parser-output cite.citation{font-style:inherit;word-wrap:break-word}.mw-parser-output .citation q{quotes:"\"""\"""'""'"}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}.mw-parser-output .id-lock-free.id-lock-free a{background:url("//upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-limited.id-lock-limited a,.mw-parser-output .id-lock-registration.id-lock-registration a{background:url("//upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-subscription.id-lock-subscription a{background:url("//upload.wikimedia.org/wikipedia/commons/a/aa/Lock-red-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .cs1-ws-icon a{background:url("//upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg")right 0.1em center/12px no-repeat}body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-free a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-limited a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-registration a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-subscription a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .cs1-ws-icon a{background-size:contain;padding:0 1em 0 0}.mw-parser-output .cs1-code{color:inherit;background:inherit;border:none;padding:inherit}.mw-parser-output .cs1-hidden-error{display:none;color:var(--color-error,#d33)}.mw-parser-output .cs1-visible-error{color:var(--color-error,#d33)}.mw-parser-output .cs1-maint{display:none;color:#085;margin-left:0.3em}.mw-parser-output .cs1-kern-left{padding-left:0.2em}.mw-parser-output .cs1-kern-right{padding-right:0.2em}.mw-parser-output .citation .mw-selflink{font-weight:inherit}@media screen{.mw-parser-output .cs1-format{font-size:95%}html.skin-theme-clientpref-night .mw-parser-output .cs1-maint{color:#18911f}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .cs1-maint{color:#18911f}}</style><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1866">1866</a>. Supplemental <a href="/wiki/Request_for_Comments" title="Request for Comments">RFCs</a> added capabilities:
<ul><li>November 25, 1995: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1867">1867</a> (form-based file upload)</li>
<li>May 1996: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1942">1942</a> (tables)</li>
<li>August 1996: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1980">1980</a> (client-side image maps)</li>
<li>January 1997: <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc2070">2070</a> (<a href="/wiki/Internationalization_and_localization" title="Internationalization and localization">internationalization</a>)</li></ul></dd></dl></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="HTML_3">HTML 3</h4></div>
<dl><dd><dl><dt>January 14, 1997</dt>
<dd>HTML 3.2<sup id="cite_ref-17" class="reference"><a href="#cite_note-17"><span class="cite-bracket">[</span>16<span class="cite-bracket">]</span></a></sup> was published as a <a href="/wiki/W3C_Recommendation" class="mw-redirect" title="W3C Recommendation">W3C Recommendation</a>. It was the first version developed and standardized exclusively by the W3C, as the IETF had closed its HTML Working Group on September 12, 1996.<sup id="cite_ref-18" class="reference"><a href="#cite_note-18"><span class="cite-bracket">[</span>17<span class="cite-bracket">]</span></a></sup></dd>
<dd>Initially code-named "Wilbur",<sup id="cite_ref-engelfriet_19-0" class="reference"><a href="#cite_note-engelfriet-19"><span class="cite-bracket">[</span>18<span class="cite-bracket">]</span></a></sup> HTML 3.2 dropped math formulas entirely, reconciled overlap among various proprietary extensions and adopted most of <a href="/wiki/Netscape" title="Netscape">Netscape</a>'s visual markup tags. Netscape's <a href="/wiki/Blink_element" title="Blink element">blink element</a> and <a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>'s <a href="/wiki/Marquee_element" title="Marquee element">marquee element</a> were omitted due to a mutual agreement between the two companies.<sup id="cite_ref-raggett_15-1" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> A markup for mathematical formulas similar to that of HTML was standardized 14 months later in <a href="/wiki/MathML" title="MathML">MathML</a>.</dd></dl></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="HTML_4">HTML 4</h4></div>
<dl><dd><dl><dt>December 18, 1997</dt>
<dd>HTML 4.0<sup id="cite_ref-20" class="reference"><a href="#cite_note-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation. It offers three variations:</dd></dl>
<dl><dt><ul><li>Strict, in which deprecated elements are forbidden</li>
<li>Transitional, in which deprecated elements are allowed</li>
<li>Frameset, in which mostly only <a href="/wiki/Framing_(World_Wide_Web)" class="mw-redirect" title="Framing (World Wide Web)">frame</a> related elements are allowed.</li></ul></dt></dl></dd>
<dd>Initially code-named "Cougar",<sup id="cite_ref-engelfriet_19-1" class="reference"><a href="#cite_note-engelfriet-19"><span class="cite-bracket">[</span>18<span class="cite-bracket">]</span></a></sup> HTML 4.0 adopted many browser-specific element types and attributes, but also sought to phase out Netscape's visual markup features by marking them as <a href="/wiki/Deprecation" title="Deprecation">deprecated</a> in favor of style sheets. HTML 4 is an SGML application conforming to ISO 8879&nbsp;– SGML.<sup id="cite_ref-21" class="reference"><a href="#cite_note-21"><span class="cite-bracket">[</span>20<span class="cite-bracket">]</span></a></sup>
<dl><dt>April 24, 1998</dt></dl></dd>
<dd>HTML 4.0<sup id="cite_ref-22" class="reference"><a href="#cite_note-22"><span class="cite-bracket">[</span>21<span class="cite-bracket">]</span></a></sup> was reissued with minor edits without incrementing the version number.
<dl><dt>December 24, 1999</dt>
<dd>HTML 4.01<sup id="cite_ref-23" class="reference"><a href="#cite_note-23"><span class="cite-bracket">[</span>22<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation. It offers the same three variations as HTML 4.0 and its last errata<sup id="cite_ref-24" class="reference"><a href="#cite_note-24"><span class="cite-bracket">[</span>23<span class="cite-bracket">]</span></a></sup> were published on May 12, 2001.</dd>
<dt>May 2000</dt>
<dd>ISO/IEC 15445:2000<sup id="cite_ref-iso-html_25-0" class="reference"><a href="#cite_note-iso-html-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup> ("<a href="/wiki/International_Organization_for_Standardization" title="International Organization for Standardization">ISO</a> HTML", based on HTML 4.01 Strict) was published as an ISO/IEC international standard.<sup id="cite_ref-26" class="reference"><a href="#cite_note-26"><span class="cite-bracket">[</span>25<span class="cite-bracket">]</span></a></sup> In the ISO, this standard is in the domain of the <a href="/wiki/ISO/IEC_JTC_1/SC_34" title="ISO/IEC JTC 1/SC 34">ISO/IEC JTC 1/SC 34</a> (ISO/IEC Joint Technical Committee 1, Subcommittee 34&nbsp;– Document description and processing languages).<sup id="cite_ref-iso-html_25-1" class="reference"><a href="#cite_note-iso-html-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup></dd></dl>
<dl><dt><dl><dd>After HTML 4.01, there were no new versions of HTML for many years, as the development of the parallel, XML-based language XHTML occupied the W3C's HTML Working Group.</dd></dl></dt></dl></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="HTML_5">HTML 5</h4></div>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1236090951"><div role="note" class="hatnote navigation-not-searchable">Main article: <a href="/wiki/HTML5" title="HTML5">HTML5</a></div>
<dl><dd><dl><dt>October 28, 2014</dt>
<dd>HTML5<sup id="cite_ref-27" class="reference"><a href="#cite_note-27"><span class="cite-bracket">[</span>26<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation.<sup id="cite_ref-28" class="reference"><a href="#cite_note-28"><span class="cite-bracket">[</span>27<span class="cite-bracket">]</span></a></sup></dd>
<dt>November 1, 2016</dt>
<dd>HTML 5.1<sup id="cite_ref-29" class="reference"><a href="#cite_note-29"><span class="cite-bracket">[</span>28<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation.<sup id="cite_ref-30" class="reference"><a href="#cite_note-30"><span class="cite-bracket">[</span>29<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-31" class="reference"><a href="#cite_note-31"><span class="cite-bracket">[</span>30<span class="cite-bracket">]</span></a></sup></dd>
<dt>December 14, 2017</dt>
<dd>HTML 5.2<sup id="cite_ref-32" class="reference"><a href="#cite_note-32"><span class="cite-bracket">[</span>31<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation.<sup id="cite_ref-33" class="reference"><a href="#cite_note-33"><span class="cite-bracket">[</span>32<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-34" class="reference"><a href="#cite_note-34"><span class="cite-bracket">[</span>33<span class="cite-bracket">]</span></a></sup></dd></dl></dd></dl>
<div class="mw-heading mw-heading3"><h3 id="HTML_draft_version_timeline">HTML draft version timeline</h3></div>
<dl><dt>October 1991</dt>
<dd><i>HTML Tags</i>,<sup id="cite_ref-tagshtml_8-1" class="reference"><a href="#cite_note-tagshtml-8"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup> an informal CERN document listing 18 HTML tags, was first mentioned in public.</dd>
<dt>June 1992</dt>
<dd>First informal draft of the HTML DTD,<sup id="cite_ref-35" class="reference"><a href="#cite_note-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup> with seven subsequent revisions (July 15, August 6, August 18, November 17, November 19, November 20, November 22)<sup id="cite_ref-36" class="reference"><a href="#cite_note-36"><span class="cite-bracket">[</span>35<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-37" class="reference"><a href="#cite_note-37"><span class="cite-bracket">[</span>36<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-html11_38-0" class="reference"><a href="#cite_note-html11-38"><span class="cite-bracket">[</span>37<span class="cite-bracket">]</span></a></sup></dd>
<dt>November 1992</dt>
<dd>HTML DTD 1.1 (the first with a version number, based on RCS revisions, which start with 1.1 rather than 1.0), an informal draft<sup id="cite_ref-html11_38-1" class="reference"><a href="#cite_note-html11-38"><span class="cite-bracket">[</span>37<span class="cite-bracket">]</span></a></sup></dd>
<dt>June 1993</dt>
<dd>Hypertext Markup Language<sup id="cite_ref-39" class="reference"><a href="#cite_note-39"><span class="cite-bracket">[</span>38<span class="cite-bracket">]</span></a></sup> was published by the <a href="/wiki/Internet_Engineering_Task_Force" title="Internet Engineering Task Force">IETF</a> IIIR Working Group as an Internet Draft (a rough proposal for a standard). It was replaced by a second version<sup id="cite_ref-ietfiiir_40-0" class="reference"><a href="#cite_note-ietfiiir-40"><span class="cite-bracket">[</span>39<span class="cite-bracket">]</span></a></sup> one month later.</dd>
<dt>November 1993</dt>
<dd><a rel="nofollow" class="external text" href="https://www.w3.org/MarkUp/HTMLPlus/htmlplus_1.html">HTML+</a> was published by the IETF as an Internet Draft and was a competing proposal to the Hypertext Markup Language draft. It expired in July 1994.<sup id="cite_ref-41" class="reference"><a href="#cite_note-41"><span class="cite-bracket">[</span>40<span class="cite-bracket">]</span></a></sup></dd>
<dt>November 1994</dt>
<dd>First draft (revision 00) of HTML 2.0 published by IETF itself<sup id="cite_ref-42" class="reference"><a href="#cite_note-42"><span class="cite-bracket">[</span>41<span class="cite-bracket">]</span></a></sup> (called as "HTML 2.0" from revision 02<sup id="cite_ref-43" class="reference"><a href="#cite_note-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup>), that finally led to the publication of <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222"><a href="/wiki/RFC_(identifier)" class="mw-redirect" title="RFC (identifier)">RFC</a>&nbsp;<a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc1866">1866</a> in November 1995.<sup id="cite_ref-rfc1866_44-0" class="reference"><a href="#cite_note-rfc1866-44"><span class="cite-bracket">[</span>43<span class="cite-bracket">]</span></a></sup></dd>
<dt>April 1995 (authored March 1995)</dt>
<dd>HTML 3.0<sup id="cite_ref-45" class="reference"><a href="#cite_note-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup> was proposed as a standard to the IETF, but the proposal expired five months later (28 September 1995)<sup id="cite_ref-html30cover_46-0" class="reference"><a href="#cite_note-html30cover-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup> without further action. It included many of the capabilities that were in Raggett's HTML+ proposal, such as support for tables, text flow around figures, and the display of complex mathematical formulas.<sup id="cite_ref-html30cover_46-1" class="reference"><a href="#cite_note-html30cover-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>W3C began development of its own <a href="/wiki/Arena_(web_browser)" title="Arena (web browser)">Arena browser</a> as a <a href="/wiki/Test_bed" class="mw-redirect" title="Test bed">test bed</a> for HTML 3 and Cascading Style Sheets,<sup id="cite_ref-47" class="reference"><a href="#cite_note-47"><span class="cite-bracket">[</span>46<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-48" class="reference"><a href="#cite_note-48"><span class="cite-bracket">[</span>47<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-49" class="reference"><a href="#cite_note-49"><span class="cite-bracket">[</span>48<span class="cite-bracket">]</span></a></sup> but HTML 3.0 did not succeed for several reasons. The draft was considered very large at 150 pages and the pace of browser development, as well as the number of interested parties, had outstripped the resources of the IETF.<sup id="cite_ref-raggett_15-2" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> Browser vendors, including Microsoft and Netscape at the time, chose to implement different subsets of HTML 3's draft features as well as to introduce their own extensions to it.<sup id="cite_ref-raggett_15-3" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> (See <a href="/wiki/Browser_wars" title="Browser wars">browser wars</a>.) These included extensions to control stylistic aspects of documents, contrary to the "belief [of the academic engineering community] that such things as text color, background texture, font size, and font face were definitely outside the scope of a language when their only intent was to specify how a document would be organized."<sup id="cite_ref-raggett_15-4" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup> Dave Raggett, who has been a W3C Fellow for many years, has commented for example: "To a certain extent, Microsoft built its business on the Web by extending HTML features."<sup id="cite_ref-raggett_15-5" class="reference"><a href="#cite_note-raggett-15"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup></dd></dl>
<figure class="mw-default-size mw-halign-right" typeof="mw:File/Thumb"><a href="/wiki/File:HTML5_logo_and_wordmark.svg" class="mw-file-description"><img alt="Official HTML5 logo" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/250px-HTML5_logo_and_wordmark.svg.png" decoding="async" width="190" height="190" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/330px-HTML5_logo_and_wordmark.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/500px-HTML5_logo_and_wordmark.svg.png 2x" data-file-width="512" data-file-height="512"></a><figcaption>Logo of HTML5</figcaption></figure>
<dl><dt>January 2008</dt>
<dd><a href="/wiki/HTML5" title="HTML5">HTML5</a> was published as a <a href="/wiki/World_Wide_Web_Consortium#Certification" title="World Wide Web Consortium">Working Draft</a> by the W3C.<sup id="cite_ref-50" class="reference"><a href="#cite_note-50"><span class="cite-bracket">[</span>49<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>Although its syntax closely resembles that of <a href="/wiki/SGML" class="mw-redirect" title="SGML">SGML</a>, <a href="/wiki/HTML5" title="HTML5">HTML5</a> has abandoned any attempt to be an SGML application and has explicitly defined its own "html" serialization, in addition to an alternative XML-based XHTML5 serialization.<sup id="cite_ref-51" class="reference"><a href="#cite_note-51"><span class="cite-bracket">[</span>50<span class="cite-bracket">]</span></a></sup></dd>
<dt>2011&nbsp;HTML5 – Last Call</dt>
<dd></dd>
<dt></dt>
<dd>On 14 February 2011, the W3C extended the charter of its HTML Working Group with clear milestones for HTML5. In May 2011, the working group advanced HTML5 to "Last Call", an invitation to communities inside and outside W3C to confirm the technical soundness of the specification. The W3C developed a comprehensive test suite to achieve broad interoperability for the full specification by 2014, which was the target date for recommendation.<sup id="cite_ref-w3c2014_52-0" class="reference"><a href="#cite_note-w3c2014-52"><span class="cite-bracket">[</span>51<span class="cite-bracket">]</span></a></sup> In January 2011, the WHATWG renamed its "HTML5" living standard to "HTML". The W3C nevertheless continued its project to release HTML5.<sup id="cite_ref-53" class="reference"><a href="#cite_note-53"><span class="cite-bracket">[</span>52<span class="cite-bracket">]</span></a></sup></dd>
<dt>2012&nbsp;HTML5 – Candidate Recommendation</dt>
<dd></dd>
<dt></dt>
<dd>In July 2012, WHATWG and <a href="/wiki/W3C" class="mw-redirect" title="W3C">W3C</a> decided on a degree of separation. W3C will continue the HTML5 specification work, focusing on a single definitive standard, which is considered a "snapshot" by WHATWG. The WHATWG organization will continue its work with HTML5 as a "Living Standard". The concept of a living standard is that it is never complete and is always being updated and improved. New features can be added but functionality will not be removed.<sup id="cite_ref-54" class="reference"><a href="#cite_note-54"><span class="cite-bracket">[</span>53<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>In December 2012, W3C designated HTML5 as a Candidate Recommendation.<sup id="cite_ref-55" class="reference"><a href="#cite_note-55"><span class="cite-bracket">[</span>54<span class="cite-bracket">]</span></a></sup> The criterion for advancement to <a href="/wiki/W3C_recommendation#W3C_recommendation_(REC)" class="mw-redirect" title="W3C recommendation">W3C Recommendation</a> is "two 100% complete and fully interoperable implementations".<sup id="cite_ref-W3Crec_56-0" class="reference"><a href="#cite_note-W3Crec-56"><span class="cite-bracket">[</span>55<span class="cite-bracket">]</span></a></sup></dd>
<dt>2014&nbsp;HTML5 – Proposed Recommendation and Recommendation</dt>
<dd></dd>
<dt></dt>
<dd>In September 2014, W3C moved HTML5 to Proposed Recommendation.<sup id="cite_ref-57" class="reference"><a href="#cite_note-57"><span class="cite-bracket">[</span>56<span class="cite-bracket">]</span></a></sup></dd>
<dt></dt>
<dd>On 28 October 2014, HTML5 was released as a stable W3C Recommendation,<sup id="cite_ref-58" class="reference"><a href="#cite_note-58"><span class="cite-bracket">[</span>57<span class="cite-bracket">]</span></a></sup> meaning the specification process is complete.<sup id="cite_ref-finalars_59-0" class="reference"><a href="#cite_note-finalars-59"><span class="cite-bracket">[</span>58<span class="cite-bracket">]</span></a></sup></dd></dl>
<div class="mw-heading mw-heading4"><h4 id="XHTML_versions">XHTML versions</h4></div>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1236090951"><div role="note" class="hatnote navigation-not-searchable">Main article: <a href="/wiki/XHTML" title="XHTML">XHTML</a></div>
<p>XHTML is a separate language that began as a reformulation of HTML 4.01 using <a href="/wiki/XML" title="XML">XML</a> 1.0. It is now referred to as <i>the XML syntax for HTML</i> and is no longer being developed as a separate standard.<sup id="cite_ref-60" class="reference"><a href="#cite_note-60"><span class="cite-bracket">[</span>59<span class="cite-bracket">]</span></a></sup>
</p>
<ul><li>XHTML 1.0 was published as a W3C Recommendation on January 26, 2000,<sup id="cite_ref-61" class="reference"><a href="#cite_note-61"><span class="cite-bracket">[</span>60<span class="cite-bracket">]</span></a></sup> and was later revised and republished on August 1, 2002. It offers the same three variations as HTML 4.0 and 4.01, reformulated in XML, with minor restrictions.</li>
<li>XHTML 1.1<sup id="cite_ref-62" class="reference"><a href="#cite_note-62"><span class="cite-bracket">[</span>61<span class="cite-bracket">]</span></a></sup> was published as a W3C Recommendation on May 31, 2001. It is based on XHTML 1.0 Strict, but includes minor changes, can be customized, and is reformulated using modules in the W3C recommendation "Modularization of XHTML", which was published on April 10, 2001.<sup id="cite_ref-63" class="reference"><a href="#cite_note-63"><span class="cite-bracket">[</span>62<span class="cite-bracket">]</span></a></sup></li>
<li>XHTML 2.0 was a working draft. Work on it was abandoned in 2009 in favor of work on <a href="/wiki/HTML5" title="HTML5">HTML5</a> and <a href="/wiki/XHTML#XHTML5" title="XHTML">XHTML5</a>.<sup id="cite_ref-64" class="reference"><a href="#cite_note-64"><span class="cite-bracket">[</span>63<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-65" class="reference"><a href="#cite_note-65"><span class="cite-bracket">[</span>64<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-66" class="reference"><a href="#cite_note-66"><span class="cite-bracket">[</span>65<span class="cite-bracket">]</span></a></sup> XHTML 2.0 was incompatible with XHTML 1.x and, therefore, would be more accurately characterized as an XHTML-inspired new language than an update to XHTML 1.x.</li></ul>
<div class="mw-heading mw-heading3"><h3 id="Transition_of_HTML_publication_to_WHATWG">Transition of HTML publication to WHATWG</h3></div>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1236090951"><div role="note" class="hatnote navigation-not-searchable">See also: <a href="/wiki/HTML5#W3C_and_WHATWG_conflict" title="HTML5">HTML5 §&nbsp;W3C and WHATWG conflict</a></div>
<p>On 28 May 2019, the W3C announced that WHATWG would be the sole publisher of the HTML and DOM standards.<sup id="cite_ref-W3C_transfer_blog_67-0" class="reference"><a href="#cite_note-W3C_transfer_blog-67"><span class="cite-bracket">[</span>66<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_HTML_68-0" class="reference"><a href="#cite_note-W3C_transfer_HTML-68"><span class="cite-bracket">[</span>67<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_memo_69-0" class="reference"><a href="#cite_note-W3C_transfer_memo-69"><span class="cite-bracket">[</span>68<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-W3C_transfer_ZDNet_70-0" class="reference"><a href="#cite_note-W3C_transfer_ZDNet-70"><span class="cite-bracket">[</span>69<span class="cite-bracket">]</span></a></sup> The W3C and WHATWG had been publishing competing standards since 2012. While the W3C standard was identical to the WHATWG in 2007 the standards have since progressively diverged due to different design decisions.<sup id="cite_ref-W3C_forks_71-0" class="reference"><a href="#cite_note-W3C_forks-71"><span class="cite-bracket">[</span>70<span class="cite-bracket">]</span></a></sup> The WHATWG "Living Standard" had been the <i>de facto</i> web standard for some time.<sup id="cite_ref-72" class="reference"><a href="#cite_note-72"><span class="cite-bracket">[</span>71<span class="cite-bracket">]</span></a></sup>
</p>
"""

# Use the part of html doucument directly (Copy and Paste the part of page into this python editor)
soup = BeautifulSoup(part_page,"html.parser")
print(soup)

History_URL_list = []
for link in soup.find_all('a'):
    print(link.get('href'))  # get the href attribute of each link
    History_URL_list.append(link.get('href')) # add the link to the list


# Use get_text to extract text from the HTML elements
url = "https://en.wikipedia.org/wiki/HTML"
req = requests.get(url)
soup = BeautifulSoup(req.content,"html.parser")

Subtitle_list = []
for link in soup.find_all('h2'):
    print(link.get_text())  # Get the text of h2 elements
    Subtitle_list.append(link.get_text()) # add the link to the list

len(Subtitle_list) # Count the number of subtitles

# Search tag with class name
table_infoboxcls=soup.find_all('table', class_="infobox")
type(table_infoboxcls)
table_parse=BeautifulSoup(str(table_infoboxcls),"html.parser")
th_res=table_parse.find_all("th",class_="infobox-label") # Find all td elements in the table

th_list = []
for elem in th_res:
    print(elem.get_text())  # Get the text of each tr element
    th_list.append(elem.get_text())

th_list

# Shift + Alt + F10 to run the code




